name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnome-shell gnome-shell-extensions
        npm ci

    - name: Build extension
      run: |
        set -e
        npm run build

    - name: Verify Build Output
      run: |
        if [ ! -f penguin-ai-chatbot@coffeecionado.gitlab.io.shell-extension.zip ]; then
          echo "Build failed! Extension ZIP file missing."
          exit 1
        fi

    - name: Create GitHub Release
      run: |
        set -e
        gh release create ${{ github.ref }} \
          ./penguin-ai-chatbot@coffeecionado.gitlab.io.shell-extension.zip \
          --title "Release ${{ github.ref }}" \
          --notes "Auto-generated release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
